<?php

declare(strict_types=1);

namespace Esegments\LaravelExtensions\Support;

use Esegments\LaravelExtensions\HandlerRegistry;

/**
 * Generates IDE helper file for extension points.
 */
final class IdeHelperGenerator
{
    public function __construct(
        private readonly HandlerRegistry $registry,
    ) {}

    /**
     * Generate IDE helper content.
     */
    public function generate(): string
    {
        $extensionPoints = $this->registry->getRegisteredExtensionPoints();

        $content = "<?php\n\n";
        $content .= "/**\n";
        $content .= " * IDE Helper for Extension Points\n";
        $content .= " * Generated by esegments/laravel-extensions\n";
        $content .= " *\n";
        $content .= " * @generated " . date('Y-m-d H:i:s') . "\n";
        $content .= " */\n\n";
        $content .= "namespace EXTENSION_HELPERS {\n\n";

        foreach ($extensionPoints as $extensionPointClass) {
            $content .= $this->generateClassHelper($extensionPointClass);
        }

        $content .= "}\n";

        return $content;
    }

    /**
     * Generate helper for a single extension point.
     */
    private function generateClassHelper(string $extensionPointClass): string
    {
        $handlers = $this->registry->getHandlers($extensionPointClass);
        $shortName = $this->getShortName($extensionPointClass);

        $content = "    /**\n";
        $content .= "     * Extension Point: {$extensionPointClass}\n";
        $content .= "     *\n";
        $content .= "     * @method static \\{$extensionPointClass} dispatch(\\{$extensionPointClass} \$event)\n";
        $content .= "     * @method static array dispatchWithResults(\\{$extensionPointClass} \$event)\n";
        $content .= "     *\n";
        $content .= "     * Registered Handlers:\n";

        foreach ($handlers as $handlerDef) {
            $handler = $handlerDef['handler'];
            if (is_string($handler)) {
                $content .= "     * @see \\{$handler}\n";
            }
        }

        $content .= "     */\n";
        $content .= "    class {$shortName} {}\n\n";

        return $content;
    }

    /**
     * Get short class name.
     */
    private function getShortName(string $className): string
    {
        $parts = explode('\\', $className);

        return array_pop($parts);
    }
}
